name: Workflow to distribute default files

on:
  workflow_dispatch: {} #to enable manual triggering of the action
jobs:

  # This job deploys the files:
  # - workflows/libraries/release-library.yml, 
  # - workflows/libraries/lint-repo.yml, 
  # - workflows/libraries/build-library.yml
  # to all repositories with the topic 'library'
  deploy_library_workflows:

      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Replicating global workflow
          uses: derberg/manage-files-in-multiple-repositories@v2
          with:
            github_token: ${{ secrets.DEPLOY_KEY }}
            patterns_to_include: workflows/libraries/release-library.yml, workflows/libraries/lint-repo.yml, workflows/libraries/build-library.yml
            destination: .github/workflows
            topics_to_include: library
            exclude_private: false
            exclude_forked: true
            committer_username: simatic-ax-bot
            commit_message: "ci: distribute workflows for libraries"
