name: Global workflow to distribute all workflow files for libraries

on:
  workflow_dispatch: {} #to enable manual triggering of the action
jobs:

  replicate_changes:

      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Replicating global workflow
          uses: derberg/manage-files-in-multiple-repositories@v2
          with:
            github_token: ${{ secrets.DEPLOY_KEY }}
            patterns_to_include: 'workflows/libraries'
            destination: .github/workflows/libraries
            topics_to_include: test
            exclude_private: true
            exclude_forked: true
            branches: main
            committer_username: simatic-ax-bot
            commit_message: "ci: distribute workflows for libraries"
